// C:\GoProject\src\eWalletGo_TestTask\errs\errs.go

package errs

import "errors"

// Ошибки кошельков
var (
	ErrRecordNotFound      = errors.New("record not found")     // Ошибка: запись не найдена...
	ErrWalletNotFound      = errors.New("wallet not found")     // Ошибка: кошелек не найден...
	ErrUniquenessViolation = errors.New("uniqueness violation") // Ошибка: нарушение уникальности...
	ErrSomethingWentWrong  = errors.New("something went wrong") // Ошибка: неизвестная ошибка сервера...
)
