basePath: /
definitions:
  controllers.ErrorResponse:
    properties:
      error:
        type: string
    type: object
host: localhost:57320
info:
  contact: {}
  description: API Server for eWalletGo Test Task Application
  title: eWalletGo API
  version: "1.0"
paths:
  /wallet/{wallet_id}/balance:
    get:
      description: Retrieves the current balance of a specified wallet
      operationId: get-wallet-balance
      parameters:
      - description: Wallet ID
        in: path
        name: wallet_id
        required: true
        type: string
      responses:
        "200":
          description: Wallet balance retrieved
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Wallet not found
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
        "500":
          description: Server error
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
      summary: Get wallet balance
      tags:
      - wallets
  /wallet/{wallet_id}/exists:
    get:
      description: Checks if the wallet exists based on wallet ID
      operationId: check-wallet-existence
      parameters:
      - description: Wallet ID
        in: path
        name: wallet_id
        required: true
        type: string
      responses:
        "200":
          description: wallet found
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Wallet not found
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
        "500":
          description: Server error
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
      summary: Check wallet existence
      tags:
      - wallets
  /wallet/{wallet_id}/recalculate-balance:
    patch:
      description: Recalculates the wallet balance based on transaction records
      operationId: recalculate-wallet-balance
      parameters:
      - description: Wallet ID
        in: path
        name: wallet_id
        required: true
        type: string
      responses:
        "200":
          description: Wallet balance recalculated
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Wallet not found
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
        "500":
          description: Server error
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
      summary: Recalculate wallet balance
      tags:
      - wallets
  /wallet/monthly-summary:
    get:
      description: Retrieves the total amount and count of recharge operations for
        a wallet in a specified month
      operationId: get-monthly-recharge-summary
      parameters:
      - description: Wallet ID
        in: query
        name: wallet_id
        required: true
        type: string
      - description: Year
        in: query
        name: year
        required: true
        type: integer
      - description: Month
        in: query
        name: month
        required: true
        type: integer
      responses:
        "200":
          description: Recharge summary retrieved
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Invalid input
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
        "404":
          description: Wallet not found
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
        "500":
          description: Server error
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
      summary: Get monthly recharge summary
      tags:
      - wallets
  /wallet/recharge:
    post:
      consumes:
      - application/json
      description: Adds a specified amount to the wallet balance
      operationId: recharge-wallet
      parameters:
      - description: Wallet ID
        in: body
        name: wallet_id
        required: true
        schema:
          type: string
      - description: Amount to recharge
        in: body
        name: amount
        required: true
        schema:
          type: number
      produces:
      - application/json
      responses:
        "200":
          description: Wallet recharged successfully
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Invalid input
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
        "404":
          description: Wallet not found
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
        "500":
          description: Server error
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
      summary: Recharge wallet
      tags:
      - wallets
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
