// C:\GoProject\src\eWalletGo_TestTask\models\account.go

package models

import (
	"time"
)

type Account struct {
	ID        uint       `gorm:"primaryKey" json:"id"`                        // Unique account identifier...
	WalletID  uint       `gorm:"not null" json:"wallet_id"`                   // Wallet ID...
	UserID    *uint      `json:"user_id"`                                     // User ID, if identified...
	Balance   float64    `gorm:"not null;default:0" json:"balance"`           // Current account balance...
	CreatedAt time.Time  `gorm:"default:CURRENT_TIMESTAMP" json:"created_at"` // Creation time...
	UpdatedAt *time.Time `json:"updated_at"`                                  // Last update time...
	DeletedAt *time.Time `json:"deleted_at"`                                  // Deletion time...
	IsDeleted bool       `gorm:"default:false" json:"is_deleted"`             // Deletion flag...

	// Relationships
	Transactions []Transaction `gorm:"foreignKey:AccountID;constraint:OnDelete:CASCADE" json:"transactions"` // Relationship with the transactions table...
}

func (Account) TableName() string {
	return "accounts"
}
