// C:\GoProject\src\eWalletGo_TestTask\models\limit_settings.go

package models

import "time"

type LimitSettings struct {
	ID            uint       `gorm:"primaryKey" json:"id"`                        // Unique limit setting identifier...
	ClientType    string     `gorm:"size:20;unique;not null" json:"client_type"`  // Client type...
	DefaultLimit  float64    `gorm:"not null" json:"default_limit"`               // Default limit...
	CustomLimit   *float64   `json:"custom_limit"`                                // Custom limit...
	AgreementDate *time.Time `json:"agreement_date"`                              // Date of custom limit agreement...
	CreatedAt     time.Time  `gorm:"default:CURRENT_TIMESTAMP" json:"created_at"` // Creation time...
	UpdatedAt     *time.Time `json:"updated_at"`                                  // Last update time...
	DeletedAt     *time.Time `json:"deleted_at"`                                  // Deletion time...
	IsDeleted     bool       `gorm:"default:false" json:"is_deleted"`             // Deletion flag...
}

func (LimitSettings) TableName() string {
	return "limit_settings"
}

// WalletWithLimit includes wallet and limit data...
type WalletWithLimit struct {
	Balance   float64 `json:"balance"`    // Wallet balance
	AccountID uint    `json:"account_id"` // Account identifier
	MaxLimit  float64 `json:"max_limit"`  // Applied limit
}
