// C:\GoProject\src\eWalletGo_TestTask\models\phone.go

package models

import "time"

type Phone struct {
	ID          uint       `gorm:"primaryKey" json:"id"`                        // Уникальный идентификатор телефона...
	UserID      *uint      `json:"user_id"`                                     // ID пользователя, если он идентифицирован...
	PhoneNumber string     `gorm:"size:15;unique;not null;index" json:"phone"`  // Номер телефона...
	CreatedAt   time.Time  `gorm:"default:CURRENT_TIMESTAMP" json:"created_at"` // Время создания...
	UpdatedAt   *time.Time `json:"updated_at"`                                  // Время последнего обновления...
	DeletedAt   *time.Time `json:"deleted_at"`                                  // Время удаления...
	IsDeleted   bool       `gorm:"default:false" json:"is_deleted"`             // Флаг удаления...

	// Связи
	Wallet Wallet `gorm:"foreignKey:PhoneID;constraint:OnDelete:CASCADE" json:"wallet"` // Связь с таблицей кошельков...
}

func (Phone) TableName() string {
	return "phones"
}
