// C:\GoProject\src\eWalletGo_TestTask\models\phone.go

package models

import "time"

type Phone struct {
	ID          uint       `gorm:"primaryKey" json:"id"`                        // Unique phone identifier...
	UserID      *uint      `json:"user_id"`                                     // User ID, if identified...
	PhoneNumber string     `gorm:"size:15;unique;not null;index" json:"phone"`  // Phone number...
	CreatedAt   time.Time  `gorm:"default:CURRENT_TIMESTAMP" json:"created_at"` // Creation time...
	UpdatedAt   *time.Time `json:"updated_at"`                                  // Last update time...
	DeletedAt   *time.Time `json:"deleted_at"`                                  // Deletion time...
	IsDeleted   bool       `gorm:"default:false" json:"is_deleted"`             // Deletion flag...

	// Relationships
	Wallet Wallet `gorm:"foreignKey:PhoneID;constraint:OnDelete:CASCADE" json:"wallet"` // Relationship with the wallets table...
}

func (Phone) TableName() string {
	return "phones"
}
