// C:\GoProject\src\eWalletGo_TestTask\models\unverified_user.go

package models

import "time"

type UnverifiedUser struct {
	ID        uint       `gorm:"primaryKey" json:"id"`                          // Unique identifier for unverified user record...
	PhoneID   uint       `gorm:"not null" json:"phone_id"`                      // Phone ID linked to the user's data...
	FullName  string     `gorm:"size:255" json:"full_name"`                     // Full name of the user...
	Email     string     `gorm:"size:255;uniqueIndex" json:"email"`             // User's email...
	Status    string     `gorm:"size:20;not null;default:active" json:"status"` // Status of the unverified user...
	CreatedAt time.Time  `gorm:"default:CURRENT_TIMESTAMP" json:"created_at"`   // Creation time...
	UpdatedAt *time.Time `json:"updated_at"`                                    // Last update time...
	DeletedAt *time.Time `json:"deleted_at"`                                    // Deletion time...
	IsDeleted bool       `gorm:"default:false" json:"is_deleted"`               // Deletion flag...
}

func (UnverifiedUser) TableName() string {
	return "unverified_users"
}
