// C:\GoProject\src\eWalletGo_TestTask\models\unverified_user.go

package models

import "time"

type UnverifiedUser struct {
	ID        uint       `gorm:"primaryKey" json:"id"`                          // Уникальный идентификатор записи неидентифицированного пользователя...
	PhoneID   uint       `gorm:"not null" json:"phone_id"`                      // ID телефона, к которому привязаны данные пользователя...
	FullName  string     `gorm:"size:255" json:"full_name"`                     // Полное имя пользователя...
	Email     string     `gorm:"size:255;uniqueIndex" json:"email"`             // Email пользователя...
	Status    string     `gorm:"size:20;not null;default:active" json:"status"` // Статус неидентифицированного пользователя...
	CreatedAt time.Time  `gorm:"default:CURRENT_TIMESTAMP" json:"created_at"`   // Время создания...
	UpdatedAt *time.Time `json:"updated_at"`                                    // Время последнего обновления...
	DeletedAt *time.Time `json:"deleted_at"`                                    // Время удаления...
	IsDeleted bool       `gorm:"default:false" json:"is_deleted"`               // Флаг удаления...
}

func (UnverifiedUser) TableName() string {
	return "unverified_users"
}
