// C:\GoProject\src\eWalletGo_TestTask\models\user_settings.go

package models

import (
	"time"
)

// UserSettings represents user settings.
type UserSettings struct {
	ID                    uint       `gorm:"primaryKey" json:"id"`                                          // Unique identifier for user settings...
	UserID                *uint      `gorm:"index" json:"user_id"`                                          // ID of the identified user...
	UnverifiedUserID      *uint      `gorm:"index" json:"unverified_user_id"`                               // ID of the unverified user...
	AddConfirmation       bool       `gorm:"default:true" json:"add_confirmation"`                          // Add confirmation...
	UpdateConfirmation    bool       `gorm:"default:true" json:"update_confirmation"`                       // Update confirmation...
	DeleteConfirmation    bool       `gorm:"default:true" json:"delete_confirmation"`                       // Delete confirmation...
	DisplayLanguage       string     `gorm:"size:255;default:'Russian'" json:"display_language"`            // Display language...
	DesktopTheme          string     `gorm:"size:255;default:'Green animation'" json:"desktop_theme"`       // Desktop theme...
	DarkModeTheme         bool       `gorm:"default:false" json:"dark_mode_theme"`                          // Dark mode...
	Font                  string     `gorm:"size:255;default:'Helvetica'" json:"font"`                      // Font...
	FontSize              int        `gorm:"default:11" json:"font_size"`                                   // Font size...
	AccessibilityOptions  string     `gorm:"size:255;default:'High contrast'" json:"accessibility_options"` // Accessibility options...
	NotificationSound     bool       `gorm:"default:true" json:"notification_sound"`                        // Notification sound...
	EmailNotifications    bool       `gorm:"default:false" json:"email_notifications"`                      // Email notifications...
	NotificationFrequency string     `gorm:"size:255" json:"notification_frequency"`                        // Notification frequency...
	CreatedAt             time.Time  `json:"created_at"`                                                    // Settings creation date...
	UpdatedAt             *time.Time `json:"updated_at"`                                                    // Last update date for settings...
	DeletedAt             *time.Time `json:"deleted_at"`                                                    // Deletion time...
	IsDeleted             bool       `gorm:"default:false" json:"is_deleted"`                               // Deletion flag...
}

// TableName sets a custom table name for the UserSettings model.
func (UserSettings) TableName() string {
	return "user_settings"
}
