// C:\GoProject\src\eWalletGo_TestTask\models\wallet.go

package models

import "time"

type Wallet struct {
	ID         uint       `gorm:"primaryKey" json:"id"`                          // Уникальный идентификатор кошелька...
	PhoneID    uint       `gorm:"not null" json:"phone_id"`                      // ID телефона...
	UserID     *uint      `json:"user_id"`                                       // ID пользователя, если он идентифицирован...
	ClientType string     `gorm:"size:20;not null" json:"client_type"`           // Тип клиента...
	Status     string     `gorm:"size:20;not null;default:active" json:"status"` // Статус кошелька (active, blocked, canceled)...
	CreatedAt  time.Time  `gorm:"default:CURRENT_TIMESTAMP" json:"created_at"`   // Время создания...
	UpdatedAt  *time.Time `json:"updated_at"`                                    // Время последнего обновления...
	DeletedAt  *time.Time `json:"deleted_at"`                                    // Время удаления...
	IsDeleted  bool       `gorm:"default:false" json:"is_deleted"`               // Флаг удаления...

	// Связи
	Accounts []Account `gorm:"foreignKey:WalletID;constraint:OnDelete:CASCADE" json:"accounts"` // Связь с таблицей счетов...
}

func (Wallet) TableName() string {
	return "wallets"
}
